package tela;

// @author a120104
import java.awt.BorderLayout;
import java.awt.Image;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import pokemons.Pokemons;

public class TelaMostrar extends javax.swing.JFrame {

    private Pokemons mostra;
    private Image image;
    private String nome;
    private String tipo;
    private String indice;
    private String x;
    private String y;
    private String z;
   
    /**
     * Creates new form TelaMostrar
     */
    public TelaMostrar() {
        initComponents();
        mostra = new Pokemons();
        image = null;
       
        
    }

    public void lerImagem() {
        setItens();
        String nomeImagem = "src/pokemonsImagens/";
        nomeImagem += this.mostra.getIndece();
        nomeImagem += ".png";   // source.gif
        try {
            // Lendo um arquivo
            File sourceimage = new File(nomeImagem);
            image = ImageIO.read(sourceimage);

            // Lendo de um input stream
           /* InputStream is = new BufferedInputStream(
                    new FileInputStream(nomeImagem));
            image = ImageIO.read(is);*/

            // Lendo de uma URL
           /* URL url = new URL("http://java-tips.org/source.gif");
            image = ImageIO.read(url);*/
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Não foi possivel abrir a imagem.");
        }
        JLabel label = new JLabel(new ImageIcon(image));
        getContentPane().add(label, BorderLayout.CENTER);
        this.jImagem.getViewport().add(label);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jImagem = new javax.swing.JScrollPane();
        jTNome = new javax.swing.JLabel();
        jTTipo = new javax.swing.JLabel();
        jTIndice = new javax.swing.JLabel();
        jTX = new javax.swing.JLabel();
        jTY = new javax.swing.JLabel();
        jTZ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pokemon Hue Hue BR");

        jTNome.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTNome.setText("nome:");

        jTTipo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTTipo.setText("Tipo:");

        jTIndice.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTIndice.setText("Indice:");

        jTX.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTX.setText("X:");

        jTY.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTY.setText("Y:");

        jTZ.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTZ.setText("Z:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jImagem, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTTipo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTX)
                            .addComponent(jTIndice))
                        .addGap(225, 225, 225)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTNome)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTZ)
                                .addGap(171, 171, 171))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jImagem, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTIndice)
                    .addComponent(jTNome))
                .addGap(18, 18, 18)
                .addComponent(jTTipo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTY)
                    .addComponent(jTZ)
                    .addComponent(jTX)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMostrar().setVisible(true);
                
            }
        });
    }
    public void setItens(){
        nome = "Nome: " + this.mostra.getNome();
        this.jTNome.setText(nome);
        indice = "Indice: " + this.mostra.getIndece();
        this.jTIndice.setText(indice);
        tipo = "Tipo: " + this.mostra.getTipo().toString();
        this.jTTipo.setText(tipo);
        x = "X: " + this.mostra.getCordenada().getX();
        this.jTX.setText(x);
        y = "Y: " + this.mostra.getCordenada().getY();
        this.jTY.setText(y);
        z = "Z: " + this.mostra.getCordenada().getZ();
        this.jTZ.setText(z);
    }
    
    public Pokemons getMostra() {
        return this.mostra;
    }

    public void setMostra(Pokemons mostra) {
        this.mostra = mostra;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jImagem;
    private javax.swing.JLabel jTIndice;
    private javax.swing.JLabel jTNome;
    private javax.swing.JLabel jTTipo;
    private javax.swing.JLabel jTX;
    private javax.swing.JLabel jTY;
    private javax.swing.JLabel jTZ;
    // End of variables declaration//GEN-END:variables
}
