package tela;

import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import local.Cordenadas;
import local.LocalizarPokemon;
import pokemons.Pokemons;

// @author a120104
public class TelaPrincipalP extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalP
     */
    private LocalizarPokemon localizar;
    private ArrayList<Pokemons> capturados;
    private int quant;

    private int cap;
    private int tentativas;
    private int tenta;
    private Random ger;
    private int linha;
    private long seed;

    public TelaPrincipalP() {
        initComponents();
        localizar = new LocalizarPokemon();
        quant = 0;
        this.cap = 0;
        this.tentativas = 0;
        ger = new Random();
        this.tenta = 0;
        linha = 0;
        this.capturados = new ArrayList<>();
        this.clik = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextQuantidade = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        JTQntGerados = new javax.swing.JLabel();
        jBCaptura = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pokemon Hue Hue BR");

        jTable2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Tipo", "X", "Y", "Z"
            }
        ));
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTable2.setName(""); // NOI18N
        jTable2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jTable2AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        jTable2.getAccessibleContext().setAccessibleName("");
        jTable2.getAccessibleContext().setAccessibleDescription("");

        jTextQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextQuantidadeActionPerformed(evt);
            }
        });

        jLabel2.setText("Quantidade de Pokemons a serem gerados:");

        jToggleButton1.setText("Gerar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        JTQntGerados.setText("Quantos Pokemons foram gerados:");

        jBCaptura.setText("Capturar");
        jBCaptura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCapturaActionPerformed(evt);
            }
        });

        jButton1.setText("Pokemons Capturados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jToggleButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBCaptura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(JTQntGerados)))
                        .addGap(0, 122, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1)
                    .addComponent(JTQntGerados)
                    .addComponent(jBCaptura)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void atualizarTabela() {
        DefaultTableModel model;

        model = (DefaultTableModel) this.jTable2.getModel();
        while (model.getRowCount() > 0) {

            model.removeRow(0);
        }
        for (int i = 0; i < this.localizar.achados.size(); i++) {

            model.addRow(new Object[]{this.localizar.achados.get(i).getIndece(), this.localizar.achados.get(i).getNome(),
                this.localizar.achados.get(i).getTipo().toString(), this.localizar.achados.get(i).getCordenada().getX(), this.localizar.achados.get(i).getCordenada().getY(), this.localizar.achados.get(i).getCordenada().getZ()});

        }
        this.jTextQuantidade.setText("");
    }

    private void jTable2AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable2AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2AncestorMoved

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if (this.jTextQuantidade != null) {
            this.converter();
            this.localizar.achados.clear();
            while (this.localizar.achados.size() != this.quant) {
                this.localizar.verificar();

            }
            this.JTQntGerados.setText("Quantos Pokemons foram gerados: " + this.localizar.achados.size());
            this.atualizarTabela();
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    public void converter() {
        try {
            this.quant = Integer.parseInt(this.jTextQuantidade.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Digite um numero.");
        }
    }

    private void jTextQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextQuantidadeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextQuantidadeActionPerformed
    private int clik;

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        clik++;
        this.linha = this.jTable2.getSelectedRow();
        long lDateTime = new Date().getTime();
        this.setSeed(lDateTime);
        this.ger.setSeed(this.getSeed());
        this.tentativas = ger.nextInt(2) + 4;
        if (clik < 2) {
            this.tenta = 0;
        } else {
            this.mostrar();
            clik = 0;
        }

    }//GEN-LAST:event_jTable2MouseClicked

    public void mostrar() {
        TelaMostrar mostra = new TelaMostrar();
        mostra.setMostra(this.localizar.achados.get(linha));
        mostra.setVisible(true);
        mostra.lerImagem();
    }

    private void jBCapturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCapturaActionPerformed
        // TODO add your handling code here:
        if (clik > 0) {
            long lDateTime = new Date().getTime();
            this.setSeed(lDateTime);
            ger.setSeed(this.getSeed());
            cap = ger.nextInt(6);
            if (this.tenta <= this.tentativas) {
                if (cap < this.tenta) {
                    JOptionPane.showMessageDialog(null, "Pokemon capturado.");
                    mostrar();
                    this.capturados.add(this.localizar.achados.get(linha));
                    this.localizar.achados.remove(linha);
                    this.clik = 0;
                    this.atualizarTabela();
                } else {
                    JOptionPane.showMessageDialog(null, "Pokemon escapou da pokebola.");
                }
                this.tenta++;
            } else {
                JOptionPane.showMessageDialog(null, "Pokemon escapou da pokebola.");
                JOptionPane.showMessageDialog(null, "Pokemon escapou.");
                this.localizar.achados.remove(linha);
                this.clik = 0;
                this.atualizarTabela();

            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Clique em alguma linha. ");
        }
    }//GEN-LAST:event_jBCapturaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TelaCapturados telaCap = new TelaCapturados();
        telaCap.setCapturados(capturados);
        telaCap.atualizarTabela();
        telaCap.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JTQntGerados;
    private javax.swing.JButton jBCaptura;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextQuantidade;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the seed
     */
    public long getSeed() {
        return seed;
    }

    /**
     * @param seed the seed to set
     */
    public void setSeed(long seed) {
        this.seed = seed;
    }
}
